// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Media;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class Songs : ResourcesBase<Song>
    {
        public Songs(ContentManager contentManager) : base(contentManager)
        {
        }

        [Description("Audio/Music/sleighride.mp3")]
        public Song sleighride { get; set; }
        [Description("Audio/Music/spongebob.mp3")]
        public Song spongebob { get; set; }
        [Description("Audio/Music/theatreland.mp3")]
        public Song theatreland { get; set; }
    }
}
