// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Media;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class Songs
    {

        [Description("Audio/Music/theatreland")]
        public Song theatreland { get; set; }
        [Description("Audio/Music/spongebob")]
        public Song spongebob { get; set; }
        [Description("Audio/Music/sleighride")]
        public Song sleighride { get; set; }
    }
}
