// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Audio;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class SoundEffects
    {

        [Description("Audio/grenade")]
        public SoundEffect grenade { get; set; }
        [Description("Audio/empty")]
        public SoundEffect empty { get; set; }
        [Description("Audio/splat1")]
        public SoundEffect splat1 { get; set; }
        [Description("Audio/smg")]
        public SoundEffect smg { get; set; }
        [Description("Audio/reload")]
        public SoundEffect reload { get; set; }
        [Description("Audio/shotgun")]
        public SoundEffect shotgun { get; set; }
        [Description("Audio/ouch1")]
        public SoundEffect ouch1 { get; set; }
    }
}
