// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Audio;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class SoundEffects : ResourcesBase<SoundEffect>
    {
        public SoundEffects(ContentManager contentManager) : base(contentManager)
        {
        }

        [Description("Audio/empty.wav")]
        public SoundEffect empty { get; set; }
        [Description("Audio/grenade.wav")]
        public SoundEffect grenade { get; set; }
        [Description("Audio/ouch1.wav")]
        public SoundEffect ouch1 { get; set; }
        [Description("Audio/reload.wav")]
        public SoundEffect reload { get; set; }
        [Description("Audio/shotgun.wav")]
        public SoundEffect shotgun { get; set; }
        [Description("Audio/smg.wav")]
        public SoundEffect smg { get; set; }
        [Description("Audio/splat1.wav")]
        public SoundEffect splat1 { get; set; }
    }
}
