// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class SpriteFonts : ResourcesBase<SpriteFont>
    {
        public SpriteFonts(ContentManager contentManager) : base(contentManager)
        {
        }

        [Description("Fonts/menuRegular.spritefont")]
        public SpriteFont menuRegular { get; set; }
        [Description("Fonts/menuSelected.spritefont")]
        public SpriteFont menuSelected { get; set; }
        [Description("Fonts/Verdana.spritefont")]
        public SpriteFont Verdana { get; set; }
    }
}
