// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Graphics;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class SpriteFonts
    {

        [Description("Fonts/Verdana")]
        public SpriteFont Verdana { get; set; }
    }
}
