// <auto-generated />
// ReSharper disable All
using System.ComponentModel;
using Microsoft.Xna.Framework.Graphics;

namespace BunnyLand.DesktopGL.Resources
{
    public partial class Textures
    {
        [Description("Textures/black-hole")]
        public Texture2D blackhole { get; set; }
        [Description("Textures/blood")]
        public Texture2D blood { get; set; }
        [Description("Textures/blood2")]
        public Texture2D blood2 { get; set; }
        [Description("Textures/bullet")]
        public Texture2D bullet { get; set; }
        [Description("Textures/bunny-sprites")]
        public Texture2D bunnysprites { get; set; }
        [Description("Textures/exp2")]
        public Texture2D exp2 { get; set; }
        [Description("Textures/Explotion")]
        public Texture2D Explotion { get; set; }
        [Description("Textures/Handweapon")]
        public Texture2D Handweapon { get; set; }
        [Description("Textures/PlayerAnimation")]
        public Texture2D PlayerAnimation { get; set; }
        [Description("Textures/testmap")]
        public Texture2D testmap { get; set; }
        [Description("Textures/totoro")]
        public Texture2D totoro { get; set; }
        [Description("Textures/Bodyparts/Body")]
        public Texture2D Body { get; set; }
        [Description("Textures/Bodyparts/Ear1")]
        public Texture2D Ear1 { get; set; }
        [Description("Textures/Bodyparts/Ear2")]
        public Texture2D Ear2 { get; set; }
        [Description("Textures/Bodyparts/Eye1")]
        public Texture2D Eye1 { get; set; }
        [Description("Textures/Bodyparts/Eye2")]
        public Texture2D Eye2 { get; set; }
        [Description("Textures/Bodyparts/Foot")]
        public Texture2D Foot { get; set; }
        [Description("Textures/Bodyparts/Hand")]
        public Texture2D Hand { get; set; }
        [Description("Textures/Bodyparts/Head")]
        public Texture2D Head { get; set; }
        [Description("Textures/Menu/cutebunnies")]
        public Texture2D cutebunnies { get; set; }
        [Description("Textures/Planets/Earth")]
        public Texture2D Earth { get; set; }
        [Description("Textures/Planets/Planet_by_Randell")]
        public Texture2D PlanetbyRandell { get; set; }
        [Description("Textures/Planets/redplanet")]
        public Texture2D redplanet { get; set; }
        [Description("Textures/Planets/Venus")]
        public Texture2D Venus { get; set; }
    }
}
